import "server-only"; import { promises as fs } from "node:fs"; import path from "node:path"; import { NextRequest,NextResponse } from "next/server"; import { getKisQuote } from "@/lib/kis-quote-provider"; import { calculateIntradayMarketAnalysis } from "@/lib/intraday-market-analysis-v1.mjs";
const codeOf=(value:string|null)=>{if(!value)return null;const code=(value.startsWith("A")&&value.length===7?value.slice(1):value).toUpperCase();return /^[0-9A-Z]{6}$/.test(code)?code:null;};
export async function GET(request:NextRequest){const code=codeOf(request.nextUrl.searchParams.get("code"));if(!code)return NextResponse.json({status:"blocked",blockingReasons:["invalidCode"]},{status:400});const root=process.cwd(),marketDir=path.join(root,"data","analysis","market"),seedDir=path.join(root,"data","analysis","market-seeds");let officialSnapshot=null,seed=null,quote=null;const blockingReasons:string[]=[];
 try{const names=(await fs.readdir(marketDir)).filter((n)=>/^\d{4}-\d{2}-\d{2}\.json$/.test(n)).sort().reverse();if(!names[0])blockingReasons.push("officialSnapshotMissing");else officialSnapshot=JSON.parse(await fs.readFile(path.join(marketDir,names[0]),"utf8"));}catch{blockingReasons.push("officialSnapshotMissing");}
 if(officialSnapshot)try{seed=JSON.parse(await fs.readFile(path.join(seedDir,`${officialSnapshot.requestedDate}.json`),"utf8"));}catch{blockingReasons.push("seedMissing");}
 try{quote=await getKisQuote(code);}catch{blockingReasons.push("kisQuoteFailed");}
 let calendarStatus=null;if(quote?.asOfDate)try{const calendar=JSON.parse(await fs.readFile(path.join(root,"data","trading-calendar","status.json"),"utf8"));calendarStatus=calendar.dates?.[quote.asOfDate]?.status??"unchecked";}catch{calendarStatus="unchecked";}else blockingReasons.push("quoteDateMissing");
 const official=officialSnapshot?.records?.find((r:{code?:string})=>r.code===code);const seedRecord=seed?.records?.find((r:{code?:string})=>r.code===code);const result=calculateIntradayMarketAnalysis({requestedDate:quote?.asOfDate??null,quote,calendarStatus,marketSessionVerified:false,marketStatusEvidence:{calendarStatus,sessionStatus:"unverified"},official:official?{asOfDate:official.asOfDate,sourceHash:officialSnapshot.sourceManifest?.sources?.officialDailyPrice?.normalizedInputHash,formulaHash:officialSnapshot.formulaHash,finalTechnicalScore:official.finalTechnicalScore}:null,seedMeta:seed?{seedVersion:seed.seedVersion}:null,seedRecord});
 return NextResponse.json({status:result.blockingReasons.length?"blocked":"provisional",quote:quote?{...quote,marketStatus:"unknown",isRealtime:false}:null,intradayAnalysis:{...result,blockingReasons:[...new Set([...blockingReasons,...result.blockingReasons])]},officialReference:official?{asOfDate:official.asOfDate,calculatorVersion:officialSnapshot.calculatorVersion,finalTechnicalScore:official.finalTechnicalScore}:null},{headers:{"Cache-Control":"no-store"}});}
