"use client";
type RecordData = { analysisAsOfDate:string; financialPeriodEnd:string|null; filingDate:string|null; fsDivision:string|null; priceBasis:string; priceAsOfDate:string|null; marketCap:number|null; qualityStatus:string; eligible:boolean; ineligibleReasons:string[]; financialMetrics:Record<string,number|null>; componentScores:{profitability:number|null;growth:number|null;stability:number|null;valuation:number|null}; totalScore:number|null; grade:string; formulaVersion:string };
export type CompanyAnalysisResult = { status:string; generatedAt:string; calculatorVersion:string; record:RecordData };
const fmt=(value:number|null|undefined,d=2)=>typeof value==="number"&&Number.isFinite(value)?value.toFixed(d):"계산 불가";
export default function CompanyAnalysisPanel({ result, loading, error }:{result:CompanyAnalysisResult|null;loading:boolean;error:string|null}) {
  if(loading) return <div className="mt-6 rounded-2xl border border-gray-200 bg-white p-5 text-sm text-gray-500">저장된 기업분석 결과를 조회하고 있습니다.</div>;
  if(error||!result) return <div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-5"><h2 className="font-bold text-red-800">기업분석 결과 없음</h2><p className="mt-2 text-sm text-red-700">{error??"저장된 결과가 없습니다."}</p><p className="mt-2 text-xs text-red-600">DART를 호출하거나 브라우저 계산·KIS 가격 fallback을 사용하지 않습니다.</p></div>;
  const r=result.record;
  if(!r.eligible) return <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">기업분석 계산 불가</h2><p className="mt-2 text-sm">{r.ineligibleReasons.join(", ")}</p></div>;
  return <div className="mt-6 rounded-2xl border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">저장된 기업분석</p><h2 className="mt-1 text-xl font-bold">기업 분석</h2><div className="mt-2 grid grid-cols-2 gap-2 text-xs text-gray-500"><span>분석 기준일 {r.analysisAsOfDate}</span><span>재무 기간 {r.financialPeriodEnd??"-"}</span><span>공시일 {r.filingDate??"-"}</span><span>{r.fsDivision==="CFS"?"연결":"별도"}</span><span>가치 기준일 {r.priceAsOfDate??"-"}</span><span>품질 {r.qualityStatus}</span><span>버전 {r.formulaVersion}</span></div><div className="mt-5 rounded-xl border p-4"><div className="flex justify-between"><span className="text-sm text-gray-500">종합 투자지표</span><strong className="text-3xl">{r.totalScore} / 100</strong></div><p className="mt-1 text-right font-semibold">{r.grade}</p>{Object.entries(r.componentScores).map(([key,value])=><div className="mt-2 flex justify-between text-sm" key={key}><span>{key}</span><span>{fmt(value,1)} / 25</span></div>)}</div><div className="mt-5 space-y-2 text-sm">{[["ROE",r.financialMetrics.roe],["영업이익률",r.financialMetrics.operatingMargin],["부채비율",r.financialMetrics.debtRatio],["PER",r.financialMetrics.per],["PBR",r.financialMetrics.pbr],["매출 CAGR",r.financialMetrics.revenueCagr],["영업이익 CAGR",r.financialMetrics.operatingProfitCagr]].map(([label,value])=><div className="flex justify-between" key={String(label)}><span>{label}</span><span>{fmt(value as number|null)}{String(label).includes("PER")||String(label).includes("PBR")?"배":"%"}</span></div>)}</div><p className="mt-5 text-xs text-gray-400">가치평가는 공식 기준일 시가총액만 사용합니다. KIS 현재가는 표시 카드와 독립적입니다.</p></div>;
}
