"use client";
type RecordData = { analysisAsOfDate:string; financialPeriodEnd:string|null; filingDate:string|null; fsDivision:string|null; priceBasis:string; priceAsOfDate:string|null; marketCap:number|null; qualityStatus:string; eligible:boolean; ineligibleReasons:string[]; financialMetrics:Record<string,number|null>; componentScores:{profitability:number|null;growth:number|null;stability:number|null;valuation:number|null}; featureProvenance?:{revenueCagr?:{calculationStatus?:string};operatingProfitCagr?:{calculationStatus?:string}}|null; totalScore:number|null; grade:string; formulaVersion:string };
export type CompanyAnalysisResult = { status:string; generatedAt:string; calculatorVersion:string; record:RecordData };
const fmt=(value:number|null|undefined,d=2)=>typeof value==="number"&&Number.isFinite(value)?value.toFixed(d):"계산 불가";
const componentLabel:Record<string,string>={profitability:"수익성",growth:"성장성",stability:"재무 안정성",valuation:"가치 수준"};
const componentKeys=["profitability","growth","stability","valuation"] as const;
const reasonLabel: Record<string, string> = {
  profitabilityNotCalculable: "수익성 계산에 필요한 재무자료가 부족합니다.",
  growthNotCalculable: "성장성 계산에 필요한 비교 기간 자료가 부족합니다.",
  stabilityNotCalculable: "재무 안정성 계산에 필요한 자료가 부족합니다.",
  valuationNotCalculable: "가치평가를 계산할 수 없습니다.",
  missingMarketCap: "기준일 시가총액 자료가 없습니다.",
  priceDateMismatch: "재무자료와 가격의 기준일이 일치하지 않습니다.",
  financialLedgerMissing: "검증된 재무제표가 아직 준비되지 않았습니다.",
  pointInTimeStatementMissing: "분석 기준일에 사용할 수 있는 재무제표가 없습니다.",
  futureFiling: "분석 기준일 이후 공시는 사용할 수 없습니다.",
  notCalculable: "현재 자료로 기업분석을 계산할 수 없습니다.",
};
export const companyAnalysisReasonLabel = (reason?: string | null) => reason ? (reasonLabel[reason] ?? "기업분석에 필요한 자료가 충분하지 않습니다.") : "기업 재무데이터를 준비하고 있습니다.";
const cagrStatusLabel:Record<string,string>={available:"확인됨",missing:"비교 입력 없음",nonPositive:"비교 입력이 0 이하"};
export default function CompanyAnalysisPanel({ result, loading, error }:{result:CompanyAnalysisResult|null;loading:boolean;error:string|null}) {
  if(loading) return <div className="mt-6 rounded-2xl border border-gray-200 bg-white p-5 text-sm text-gray-500">저장된 기업분석 결과를 조회하고 있습니다.</div>;
  if(error||!result) return <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">기업 재무데이터 준비 중</h2><p className="mt-2 text-sm text-amber-800">{error??"검증된 기업분석 결과가 아직 준비되지 않았습니다."}</p><p className="mt-2 text-xs text-amber-700">확인되지 않은 재무정보나 현재가로 대신 계산하지 않습니다.</p></div>;
  const r=result.record;
  if(!r.eligible&&Object.keys(r.financialMetrics??{}).length===0) return <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">기업분석 계산 불가</h2><div className="mt-2 space-y-1 text-sm text-amber-800">{r.ineligibleReasons.length ? r.ineligibleReasons.map((reason) => <p key={reason}>{companyAnalysisReasonLabel(reason)}</p>) : <p>{companyAnalysisReasonLabel()}</p>}</div></div>;
  return <div className={`mt-6 rounded-2xl border p-5 ${r.eligible?"border-gray-200 bg-white":"border-amber-200 bg-amber-50"}`}><p className="text-sm text-gray-500">{r.eligible?"검증된 저장 결과":"부분 분석 결과"}</p><h2 className="mt-1 text-xl font-bold">기업 분석</h2><div className="mt-2 text-xs text-gray-500">분석 기준일 {r.analysisAsOfDate} · 재무 기간 {r.financialPeriodEnd??"-"}</div>{!r.eligible&&<><div className="mt-3 space-y-1 text-sm text-amber-800">{r.ineligibleReasons.length ? r.ineligibleReasons.map((reason) => <p key={reason}>{companyAnalysisReasonLabel(reason)}</p>) : <p>{companyAnalysisReasonLabel()}</p>}</div><p className="mt-2 text-xs text-amber-800">공식 종합점수와 등급은 산정 전입니다. 계산 가능한 개별 지표만 참고용으로 표시합니다.</p></>}<div className="mt-5 rounded-xl border bg-white p-4"><div className="flex justify-between"><span className="text-sm text-gray-500">종합 투자지표</span><strong className={r.eligible?"text-3xl":"text-lg"}>{r.eligible?`${r.totalScore} / 100`:"종합점수 산정 전"}</strong></div>{r.eligible&&<p className="mt-1 text-right font-semibold">{r.grade}</p>}{componentKeys.map((key)=><div className="mt-2 flex justify-between text-sm" key={key}><span>{componentLabel[key]}</span><span>{r.componentScores[key]==null?<span className="text-gray-500">{companyAnalysisReasonLabel(`${key}NotCalculable`)}</span>:`${fmt(r.componentScores[key],1)} / 25`}</span></div>)}</div><details className="mt-5 rounded-xl border border-gray-200 bg-gray-50"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">상세 재무지표 보기</summary><div className="space-y-2 border-t p-4 text-sm">{[["ROE",r.financialMetrics.roe,"%"],["영업이익률",r.financialMetrics.operatingMargin,"%"],["부채비율",r.financialMetrics.debtRatio,"%"],["이자보상배율",r.financialMetrics.interestCoverage,"배"],["PER",r.financialMetrics.per,"배"],["PBR",r.financialMetrics.pbr,"배"],["매출 CAGR",r.financialMetrics.revenueCagr,"%"],["영업이익 CAGR",r.financialMetrics.operatingProfitCagr,"%"]].map(([label,value,unit])=><div className="flex justify-between" key={String(label)}><span>{label}</span><span>{fmt(value as number|null)}{value==null?"":unit}</span></div>)}</div></details><details className="mt-3 text-xs text-gray-500"><summary className="cursor-pointer font-medium">데이터 기준 자세히 보기</summary><div className="mt-2 grid grid-cols-2 gap-2"><span>공시일 {r.filingDate??"-"}</span><span>{r.fsDivision==="CFS"?"연결 재무제표":"별도 재무제표"}</span><span>가치 기준일 {r.priceAsOfDate??"-"}</span><span>상태 {r.qualityStatus==="PROVISIONAL"?"데이터 검증 중":r.qualityStatus}</span><span>분석 버전 {r.formulaVersion}</span>{r.featureProvenance?.revenueCagr&&<span>매출 CAGR 입력 {cagrStatusLabel[r.featureProvenance.revenueCagr.calculationStatus??""]??"확인 불가"}</span>}{r.featureProvenance?.operatingProfitCagr&&<span>영업이익 CAGR 입력 {cagrStatusLabel[r.featureProvenance.operatingProfitCagr.calculationStatus??""]??"확인 불가"}</span>}</div></details><p className="mt-5 text-xs text-gray-400">가치평가는 공식 기준일 시가총액만 사용합니다. KIS 현재가는 표시 카드와 독립적입니다.</p></div>;
}
