"use client";

import { useEffect, useRef, useState } from "react";
import { dailyOperationState, latestOneDayPerformance } from "../lib/home-dashboard.mjs";

type Stock = { code: string; name: string };
type Ranked = Stock & { rank: number; score: number; rankRise?: number };
type Model = { modelVersion: string; rankingUniverseCount: number; comparisonStatus: string; comparisonReason: string | null; top: Ranked[]; entered: Ranked[] | null; exited: Ranked[] | null; risers: Ranked[] | null; universeAddedTop: Ranked[] | null; universeRemovedTop: Ranked[] | null };
type Transition = { referenceDate: string; ruleVersion: string; indicatorCoverage: number; totalUniverse: number; excludedCount: number; sourceQualityGrade: string; isPartialRanking: boolean; pairs: { pair: string; states: { state: string; count: number; examples: (Stock & { topModels: string[]; gapPercent: number; shortSlopePercent: number; crossDate: string | null; aboveTradingDays: number })[] }[] }[] };
type Dashboard = { referenceDate: string | null; models: { referenceDate: string; previousOfficialDate: string | null; topN: number; models: Model[]; overlap: (Stock & { models: string[] })[] } | null; transitions: Transition | null; calendar: { today: string; time: string; dayStatus: string; expectedTradingDate: string | null } | null; liveStatus: { status: string; signalDate: string | null; updatedAt: string | null } | null };
type PerformanceRow = { modelVersion: string; horizon: string; topN: number; signalDate: string; targetTradingDate: string | null; observationCount: number; rankedConstituentCount: number; meanReturn: number | null; positiveRate: number | null };
type Performance = { daily: PerformanceRow[]; live?: { daily: PerformanceRow[] } };
type Operations = { lastAutomaticRunAt?: string | null; lastAutomaticRunConclusion?: string | null; lastSuccessAt?: string | null; siteApiReferenceDate?: string | null; latestConfirmedTradingDate?: string | null; recentFailureReason?: string | null; freshnessStatus?: string; publicationStatus?: string; siteApiMatchesPublished?: boolean; runStatus?: string; lagTradingDays?: number | null };

function useResource<T>(url: string) {
  const [state, setState] = useState<{ url: string; data: T | null; error: boolean } | null>(null);
  const sequence = useRef(0);
  useEffect(() => {
    let controller: AbortController | null = null;
    const load = () => {
      controller?.abort(); controller = new AbortController();
      const signal = controller.signal, id = ++sequence.current;
      void fetch(url, { cache: "no-store", signal }).then(async (response) => {
        if (!response.ok) throw new Error("UNAVAILABLE");
        return response.json() as Promise<T>;
      }).then((data) => { if (!signal.aborted && id === sequence.current) setState({ url, data, error: false }); })
        .catch(() => { if (!signal.aborted && id === sequence.current) setState({ url, data: null, error: true }); });
    };
    load();
    const refresh = () => { if (!document.hidden) load(); };
    const timer = window.setInterval(refresh, 60_000);
    document.addEventListener("visibilitychange", refresh);
    return () => { sequence.current += 1; controller?.abort(); window.clearInterval(timer); document.removeEventListener("visibilitychange", refresh); };
  }, [url]);
  return state?.url === url ? state : { url, data: null, error: false };
}

const label: Record<string, string> = { APPROACHING: "접근 중", CROSS_OCCURRED: "교차 발생", CONFIRMED: "교차 후 확인", NORMAL: "정상", WAITING: "갱신 대기", DELAYED: "데이터 지연", FAILED: "수집 실패", UNKNOWN: "확인 불가" };
const percent = (value: number | null | undefined) => Number.isFinite(value) ? `${Number(value) > 0 ? "+" : ""}${Number(value).toFixed(2)}%` : "미확인";
const tone = (value: number | null | undefined) => Number(value) > 0 ? "text-red-600" : Number(value) < 0 ? "text-blue-600" : "text-slate-600";
const time = (value: string | null | undefined) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString("ko-KR", { timeZone: "Asia/Seoul", hour12: false }) + " KST" : "확인 불가";

export default function HomeDashboard({ onSelectStock, onOpenModel, onOpenPerformance, onOpenTransition }: {
  onSelectStock: (stock: Stock) => void | Promise<void>; onOpenModel: (model: string) => void; onOpenPerformance: () => void; onOpenTransition: (pair: string, state: string) => void;
}) {
  const [topN, setTopN] = useState(5);
  const dashboard = useResource<Dashboard>(`/api/home-dashboard?topN=${topN}`);
  const performance = useResource<Performance>("/api/model-performance");
  const operations = useResource<Operations>("/api/daily-production-status");
  const live = useResource<{ signalDate: string; collectionCompletedAt: string }>("/api/intraday-model-top?model=B&limit=1");
  const data = dashboard.data, modelData = data?.models, transitions = data?.transitions;
  const outcome = performance.data ? latestOneDayPerformance(performance.data, topN) : null;
  const operation = dailyOperationState(operations.data, data?.calendar);
  const stockButton = (stock: Stock) => <button type="button" onClick={() => void onSelectStock(stock)} className="tb-focus max-w-full break-words rounded text-left font-medium text-slate-900 hover:text-[var(--tb-orange)]">{stock.name}<span className="ml-1 text-[10px] font-normal text-slate-500">{stock.code}</span></button>;
  const list = (rows: Ranked[] | null | undefined, fallback: string) => rows?.length ? rows.slice(0, 3).map((row) => <div key={row.code} className="flex items-baseline justify-between gap-2 py-0.5">{stockButton(row)}<span className="shrink-0 text-[10px] text-slate-600">{row.rankRise ? `↑${row.rankRise}` : `${row.rank}위`}</span></div>) : <p className="py-0.5 text-xs text-slate-500">{fallback}</p>;
  return <section className="space-y-3" aria-labelledby="home-dashboard-heading">
    <div className="flex flex-wrap items-center justify-between gap-2 text-slate-100"><div><p className="text-[10px] uppercase tracking-[0.14em] text-[#dbb296]">Daily research overview</p><h1 id="home-dashboard-heading" className="text-xl font-medium">오늘의 분석 대시보드</h1></div><span className="text-xs text-slate-200">공식 저장 기준 {data?.referenceDate ?? "확인 중"}</span></div>
    <div className="tb-market-status-panel flex flex-wrap gap-x-5 gap-y-1 px-3 py-2 text-xs text-slate-200" aria-label="시장 데이터 연결 상태">{["KOSPI", "KOSDAQ", "USD/KRW", "국내 거래대금"].map((item) => <span key={item}>{item} <span className="text-slate-400">미연결</span></span>)}<span className="ml-auto text-[10px] text-slate-400">검증된 소스 연결 후 제공</span></div>
    <div className="grid min-w-0 gap-3 xl:grid-cols-[minmax(0,1.65fr)_minmax(0,1fr)]">
      <div className="min-w-0 space-y-3">
      <section className="tb-card min-w-0 p-4" aria-labelledby="home-model-heading">
        <div className="flex flex-wrap items-center justify-between gap-2"><h2 id="home-model-heading" className="text-base font-semibold">모델 TOP 변화 · Daily EOD</h2><label className="text-xs text-slate-600">비교 범위 <select aria-label="홈 TOP 범위" value={topN} onChange={(e) => setTopN(Number(e.target.value))} className="tb-focus rounded border border-slate-200 bg-[#f8f5ef] px-2 py-1">{[5, 10, 20].map((n) => <option key={n} value={n}>TOP{n}</option>)}</select></label></div>
        <p className="mt-1 text-[11px] text-slate-600">{modelData ? `${modelData.previousOfficialDate ?? "직전 거래일 미확인"} → ${modelData.referenceDate} · 동결된 동일 모델 순위 비교` : dashboard.error ? "순위 조회 실패" : "저장 순위 확인 중"}</p>
        {modelData ? <div className="mt-3 grid gap-3 sm:grid-cols-2">{modelData.models.map((model) => <article key={model.modelVersion} className="min-w-0 rounded-lg border border-slate-200/70 bg-[rgba(250,247,241,0.87)] p-3"><button type="button" onClick={() => onOpenModel(model.modelVersion === "A-v1" ? "A-v1" : model.modelVersion[0])} className="tb-focus rounded text-sm font-semibold text-[var(--tb-orange)]">모델 {model.modelVersion[0]} →</button><span className="ml-2 text-[10px] text-slate-500">유니버스 {model.rankingUniverseCount}</span><div className="mt-2 text-xs"><p className="text-[10px] text-slate-500">신규 진입 {model.entered?.length ?? "—"} · 이탈 {model.exited?.length ?? "—"}</p>{model.comparisonStatus === "AVAILABLE" ? <><div className="mt-1">{list(model.entered, "신규 진입 없음")}</div><p className="mt-2 text-[10px] text-slate-500">TOP 내 순위 상승 {model.risers?.length ?? 0}</p>{list(model.risers, "순위 상승 없음")}<details className="mt-2"><summary className="tb-focus cursor-pointer rounded text-[11px] text-slate-600">이탈 · 유니버스 변화</summary>{list(model.exited, "TOP 이탈 없음")}<p className="mt-1 text-[10px] text-slate-500">유니버스 편입 TOP {model.universeAddedTop?.length ?? 0} · 유니버스 제외 TOP {model.universeRemovedTop?.length ?? 0} (신규·이탈과 별도)</p>{list(model.universeAddedTop, "편입 없음")}{list(model.universeRemovedTop, "제외 없음")}</details></> : <div className="mt-2"><p className="text-[11px] text-amber-800">{model.comparisonReason === "FORMULA_PROVENANCE_CHANGED_OR_MISSING" ? "저장된 공식 provenance hash가 달라 비교 보류" : "직전 거래일 snapshot 확인 불가 · 비교 보류"}</p><p className="mt-1 text-[10px] text-slate-500">현재 TOP (변화 판정 없음)</p>{list(model.top, "저장 TOP 없음")}</div>}</div></article>)}</div> : <p className="py-6 text-sm text-slate-600">{dashboard.error ? "데이터 없음 · 재조회 대기" : data ? "검증 가능한 저장 순위 없음" : "조회 중"}</p>}
        {modelData && <div className="mt-3 border-t border-slate-200/70 pt-2 text-xs"><p className="text-[11px] font-medium text-slate-600">복수 모델 TOP{topN} 교집합 {modelData.overlap.length}종목</p><div className="mt-1 flex flex-wrap gap-x-3 gap-y-1">{modelData.overlap.slice(0, 4).map((row) => <span key={row.code}>{stockButton(row)} <span className="text-[10px] text-slate-500">{row.models.map((m) => m[0]).join("/")}</span></span>)}{!modelData.overlap.length && <span className="text-slate-500">해당 조건 종목 없음</span>}</div></div>}
      </section>
      <section className="tb-card min-w-0 p-4" aria-labelledby="home-performance-heading"><div className="flex items-center justify-between gap-2"><h2 id="home-performance-heading" className="text-base font-semibold">최근 확정 1D 성과 · TOP{topN}</h2><button type="button" onClick={onOpenPerformance} className="tb-focus rounded text-xs text-[var(--tb-orange)]">상세 →</button></div><p className="mt-1 text-[10px] text-slate-600">최신 확정 신호일 단면 · 기간 누적 평균 아님 · 개별 종목 관측은 독립 시간 표본이 아닙니다.</p>{(["daily", "live"] as const).map((layer) => <div key={layer} className="mt-3"><p className="text-xs font-semibold text-slate-700">{layer === "daily" ? "Daily EOD · 신호일 종가 → 다음 거래일 종가 (예측 성과)" : "14:30 LIVE · 별도 실행 계약"}</p><div className="mt-1 grid grid-cols-2 gap-2 sm:grid-cols-4">{outcome?.[layer].map((row) => <div key={row.modelVersion} className="min-w-0 rounded-lg bg-[rgba(250,247,241,0.88)] p-2 text-xs"><span className="font-semibold">{row.modelVersion[0]}</span>{row.observationCount ? <><p className={`mt-1 font-semibold tabular-nums ${tone(row.meanReturn)}`}>{percent(row.meanReturn)}</p><p className="mt-1 text-[10px] text-slate-600">상승 {Number.isFinite(row.positiveRate) ? Number(row.positiveRate).toFixed(0) + "%" : "미확인"}<br />관측 {row.observationCount}건<br />신호 {row.signalDate}<br />결과 {row.resultDate ?? "미확인"}</p></> : <p className="mt-1 text-[11px] text-slate-500">데이터 축적 중</p>}</div>) ?? <p className="col-span-2 sm:col-span-4 py-2 text-xs text-slate-500">{performance.error ? "성과 조회 실패" : "성과 데이터 확인 중"}</p>}</div></div>)}<p className="mt-2 text-[10px] text-slate-600">확정 outcome만 포함 · 신호일 단면 1개 · 미성숙 값은 제외 · 모델 우열 판정 없음</p></section>
      </div>
      <div className="min-w-0 space-y-3">
      <section className="tb-card min-w-0 p-4" aria-labelledby="home-transition-heading"><h2 id="home-transition-heading" className="text-base font-semibold">전환 신호 · 연구용</h2><p className="mt-1 text-[11px] text-slate-600">매수 추천이 아닙니다. {transitions ? `${transitions.referenceDate} · 지표 ${transitions.indicatorCoverage}/${transitions.totalUniverse} · 제외 ${transitions.excludedCount}` : "데이터 확인 중"}</p>{transitions ? <div className="mt-3 space-y-3">{transitions.pairs.map((pair) => <div key={pair.pair}><p className="mb-1 text-xs font-semibold text-slate-700">{pair.pair.replace("-", "/")}일 이동평균선</p>{pair.states.map((state) => <div key={state.state} className="border-t border-slate-200/70 py-2"><button type="button" onClick={() => onOpenTransition(pair.pair, state.state)} className="tb-focus flex w-full items-center justify-between rounded text-xs font-medium text-slate-900"><span>{label[state.state]}</span><span className="text-[var(--tb-orange)]">{state.count}종목 →</span></button><div className="mt-1 space-y-1 text-xs">{state.examples.slice(0, 1).map((row) => <div key={row.code}>{stockButton(row)} <span className="text-[10px] text-slate-500">간격 {percent(row.gapPercent)}{row.topModels.length ? ` · TOP ${row.topModels.map((m) => m[0]).join("/")}` : ""}</span></div>)}{!state.count && <p className="text-[11px] text-slate-500">{transitions.indicatorCoverage ? "해당 조건 종목 없음" : "데이터 없음"}</p>}</div></div>)}</div>)}<p className="text-[10px] text-slate-500">{transitions.ruleVersion} · 원천 전체 품질 {transitions.sourceQualityGrade}{transitions.isPartialRanking ? " · 부분 ranking" : ""} · 개별 입력 검증 통과 종목만</p></div> : <p className="py-6 text-sm text-slate-600">{data || dashboard.error ? "전환 지표 데이터 없음 · 다른 영역과 독립" : "조회 중"}</p>}</section>
      <section className="tb-card min-w-0 p-4" aria-labelledby="home-operations-heading"><div className="flex items-center justify-between gap-2"><h2 id="home-operations-heading" className="text-base font-semibold">데이터 운영 상태</h2><span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-700">{label[operation]}</span></div><dl className="mt-3 space-y-2 text-xs text-slate-700"><div className="flex justify-between gap-3"><dt>사이트 Daily EOD</dt><dd>{operations.data?.siteApiReferenceDate ?? "확인 불가"}</dd></div><div className="flex justify-between gap-3"><dt>마지막 자동 실행</dt><dd className="text-right">{time(operations.data?.lastAutomaticRunAt)}<br /><span className="text-[10px] text-slate-500">실행 결과 {operations.data?.lastAutomaticRunConclusion ?? "미확인"} ≠ 게시 성공</span></dd></div><div className="flex justify-between gap-3"><dt>마지막 자동 게시 성공</dt><dd>확인 불가 (별도 성공 계보 없음)</dd></div><div className="flex justify-between gap-3"><dt>저장 성공시각 (API 기록)</dt><dd className="text-right">{time(operations.data?.lastSuccessAt)}</dd></div><div className="flex justify-between gap-3"><dt>확인된 최신 공식 거래일</dt><dd>{operations.data?.latestConfirmedTradingDate ?? "확인 불가"}</dd></div><div className="flex justify-between gap-3"><dt>게시 / 지연</dt><dd>{operations.data?.siteApiMatchesPublished ? "저장 게시일 일치" : "게시 확인 불가"} · {operations.data?.lagTradingDays ?? "미확인"}거래일</dd></div><div className="flex justify-between gap-3"><dt>14:30 LIVE</dt><dd className="text-right">{data?.liveStatus?.status === "FAILED" || data?.liveStatus?.status === "FAILED_COLLECTION" ? `수집 실패 · ${data.liveStatus.signalDate ?? "날짜 미확인"}` : data?.liveStatus?.status === "WAITING" ? "생성 대기" : live.data ? `최근 성공 ${live.data.signalDate}` : "확인 불가 / 관측 대기"}{live.data && <p className="mt-1 text-[10px]">검증된 최근 관측 {live.data.signalDate}</p>}</dd></div></dl><p className="mt-3 border-t border-slate-200/70 pt-2 text-[10px] leading-relaxed text-slate-600">달력 상태 {data?.calendar?.dayStatus === "marketClosed" ? "확인된 휴장 / 주말" : data?.calendar?.dayStatus === "tradingDay" ? "확인된 거래일" : "미확인"} · {operation === "UNKNOWN" ? "현재 거래일·게시 최신성을 확정할 근거가 부족합니다." : "거래일 상태와 게시 기준일을 함께 확인합니다."} Actions 성공만으로 최신 게시를 판정하지 않습니다.{operations.data?.recentFailureReason ? " 최근 실패 기록 있음 · 운영 API에서 원인 확인" : ""}</p></section>
      </div>
    </div>
  </section>;
}
